name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
    paths:
      - 'application/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd application
        npm install --legacy-peer-deps
    - name: Build
      run: |
        cd application
        npm run build
    - name: Deploy to Firebase
      run: |
        cd application
        firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
